version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: planner_db
    restart: always
    environment:
      POSTGRES_USER: planner_user
      POSTGRES_PASSWORD: planner_password
      POSTGRES_DB: planner_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: